rm_hw:
  bus:
    - can0
  loop_frequency: 1000
  cycle_time_error_threshold: 0.001
  thread_priority: 95
  # Configurations of the actuators
  actuators:
    joint1_motor:
      bus: can0
      id: 0x202
      type: rm_3508
      lp_cutoff_frequency: 150